apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx-app
    env: dev
    type: frontend

spec:
  containers:
    - name: nginx-container
      image: nginx:1.28
      ports:
      - containerPort: 80